### ISSUE TITLE
[Feature Request] Add a dockerfile

### ISSUE THREAD

**Issue by Middlepepper** [Fallenbagel/seerr-route#4]
This might be a bit to much lol, but I think this could be dockerised pretty easily though I'm new to it. Something like the below should work.

```
FROM python:3

ENV seerr_baseurl ''
ENV seerr_api_key ''
ENV movieFolder_Animemovies ''
ENV movieFolder_Cartoon '' 
ENV tvFolder_documentary ''
ENV tvFolder_Animatedseries ''
ENV tvFolder_documentary ''
ENV tvFolder_reality ''

ADD requirements.txt /

RUN pip install -r requirements.txt

ADD main.py /

CMD [ "python", "./main.py" ] 
```

**Comment by fallenbagel** [comment]
Oh yeah. Once I merge your .env support this should be perfect. I could setup some github CI to automatically build docker images when commits are made
